# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-atmos-terraform-drift-remediation
  description: Atmos Terraform Drift Remediation
  homepage: https://cloudposse.com/accelerate
  topics: ""

